[custom]
ruleset=DIRECT,https://raw.githubusercontent.com/DreamYuande/data-boom/refs/heads/master/add_direct_rule.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/DreamYuande/data-boom/refs/heads/master/add_rule.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=DIRECT,[]GEOIP,LAN
ruleset=DIRECT,[]GEOIP,CN
ruleset=🚀 节点选择,[]FINAL

# 1. 自动选择组：自动挑选延迟最低的节点
custom_proxy_group=⚡️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

# 2. 故障转移组：按顺序可用性切换，第一个挂了换第二个
custom_proxy_group=🛡️ 故障转移`fallback`.*`http://www.gstatic.com/generate_204`300

# 3. 节点切换组：手动选择单个节点
custom_proxy_group=🖐️ 手动切换`select`.*

# 4. 主选择逻辑：整合上述三个选项以及所有单个节点
custom_proxy_group=🚀 节点选择`select`[]⚡️ 自动选择`[]🛡️ 故障转移`[]🖐️ 手动切换`.*

enable_rule_generator=true
overwrite_original_rules=true
